# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import banking_pb2 as banking__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in banking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountServiceStub(object):
    """---------------------- SERVICES ----------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getBalance = channel.unary_unary(
                '/banking.AccountService/getBalance',
                request_serializer=banking__pb2.AccountRequest.SerializeToString,
                response_deserializer=banking__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.updateBalance = channel.unary_unary(
                '/banking.AccountService/updateBalance',
                request_serializer=banking__pb2.UpdateBalanceRequest.SerializeToString,
                response_deserializer=banking__pb2.BalanceResponse.FromString,
                _registered_method=True)


class AccountServiceServicer(object):
    """---------------------- SERVICES ----------------------

    """

    def getBalance(self, request, context):
        """Retrieve the current balance of a user's account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateBalance(self, request, context):
        """Update the balance after a transaction (amount can be +ve or -ve).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.getBalance,
                    request_deserializer=banking__pb2.AccountRequest.FromString,
                    response_serializer=banking__pb2.BalanceResponse.SerializeToString,
            ),
            'updateBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.updateBalance,
                    request_deserializer=banking__pb2.UpdateBalanceRequest.FromString,
                    response_serializer=banking__pb2.BalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'banking.AccountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('banking.AccountService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountService(object):
    """---------------------- SERVICES ----------------------

    """

    @staticmethod
    def getBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.AccountService/getBalance',
            banking__pb2.AccountRequest.SerializeToString,
            banking__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.AccountService/updateBalance',
            banking__pb2.UpdateBalanceRequest.SerializeToString,
            banking__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TransactionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.initiateTransfer = channel.unary_unary(
                '/banking.TransactionService/initiateTransfer',
                request_serializer=banking__pb2.TransferRequest.SerializeToString,
                response_deserializer=banking__pb2.TransferResponse.FromString,
                _registered_method=True)
        self.getTransactionHistory = channel.unary_unary(
                '/banking.TransactionService/getTransactionHistory',
                request_serializer=banking__pb2.TransactionHistoryRequest.SerializeToString,
                response_deserializer=banking__pb2.TransactionHistoryResponse.FromString,
                _registered_method=True)


class TransactionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def initiateTransfer(self, request, context):
        """Initiates a transfer from one account to another.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTransactionHistory(self, request, context):
        """Retrieves a list of transactions for a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'initiateTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.initiateTransfer,
                    request_deserializer=banking__pb2.TransferRequest.FromString,
                    response_serializer=banking__pb2.TransferResponse.SerializeToString,
            ),
            'getTransactionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.getTransactionHistory,
                    request_deserializer=banking__pb2.TransactionHistoryRequest.FromString,
                    response_serializer=banking__pb2.TransactionHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'banking.TransactionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('banking.TransactionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransactionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def initiateTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.TransactionService/initiateTransfer',
            banking__pb2.TransferRequest.SerializeToString,
            banking__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTransactionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.TransactionService/getTransactionHistory',
            banking__pb2.TransactionHistoryRequest.SerializeToString,
            banking__pb2.TransactionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
