# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'banking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbanking.proto\x12\x07\x62\x61nking\"!\n\x0e\x41\x63\x63ountRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"D\n\x0f\x42\x61lanceResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x01\x12\x0f\n\x07message\x18\x03 \x01(\t\"7\n\x14UpdateBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"`\n\x0fTransferRequest\x12\x14\n\x0c\x66rom_user_id\x18\x01 \x01(\t\x12\x12\n\nto_user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"f\n\x10TransferResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x10\x66rom_new_balance\x18\x03 \x01(\x01\x12\x16\n\x0eto_new_balance\x18\x04 \x01(\x01\"\x87\x01\n\x0bTransaction\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66rom_user_id\x18\x02 \x01(\t\x12\x12\n\nto_user_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\",\n\x19TransactionHistoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"H\n\x1aTransactionHistoryResponse\x12*\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x14.banking.Transaction2\x9b\x01\n\x0e\x41\x63\x63ountService\x12?\n\ngetBalance\x12\x17.banking.AccountRequest\x1a\x18.banking.BalanceResponse\x12H\n\rupdateBalance\x12\x1d.banking.UpdateBalanceRequest\x1a\x18.banking.BalanceResponse2\xbf\x01\n\x12TransactionService\x12G\n\x10initiateTransfer\x12\x18.banking.TransferRequest\x1a\x19.banking.TransferResponse\x12`\n\x15getTransactionHistory\x12\".banking.TransactionHistoryRequest\x1a#.banking.TransactionHistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTREQUEST']._serialized_start=26
  _globals['_ACCOUNTREQUEST']._serialized_end=59
  _globals['_BALANCERESPONSE']._serialized_start=61
  _globals['_BALANCERESPONSE']._serialized_end=129
  _globals['_UPDATEBALANCEREQUEST']._serialized_start=131
  _globals['_UPDATEBALANCEREQUEST']._serialized_end=186
  _globals['_TRANSFERREQUEST']._serialized_start=188
  _globals['_TRANSFERREQUEST']._serialized_end=284
  _globals['_TRANSFERRESPONSE']._serialized_start=286
  _globals['_TRANSFERRESPONSE']._serialized_end=388
  _globals['_TRANSACTION']._serialized_start=391
  _globals['_TRANSACTION']._serialized_end=526
  _globals['_TRANSACTIONHISTORYREQUEST']._serialized_start=528
  _globals['_TRANSACTIONHISTORYREQUEST']._serialized_end=572
  _globals['_TRANSACTIONHISTORYRESPONSE']._serialized_start=574
  _globals['_TRANSACTIONHISTORYRESPONSE']._serialized_end=646
  _globals['_ACCOUNTSERVICE']._serialized_start=649
  _globals['_ACCOUNTSERVICE']._serialized_end=804
  _globals['_TRANSACTIONSERVICE']._serialized_start=807
  _globals['_TRANSACTIONSERVICE']._serialized_end=998
# @@protoc_insertion_point(module_scope)
